### ISSUE TITLE
Percentage calculation seems way off

### ISSUE THREAD

**Issue by simonneutert** [D-Niermann/BreadCalculator#10]
I have a question regarding the percentage calculation.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/8125726/147872632-0bd401bc-3fa1-48cd-b47e-f024d26d8299.png">

to me, the base of the percentage calculation seems off ... can you explain, please? For the screenshot, I didn't fiddle with the percentage inputs themselves.

let me know if I can help 🇩🇪

**Comment by D-Niermann** [comment]
Hi Simon! First, thanks for all your feedback. What's the problem exactly here? Percentages for bread doughs are most of the time calculated to the total amount of flour. I think everything is correct.
Und ja du kannst mir sicherlich helfen, ich hätte ein paar Fragen :) Wenn du willst kannst du mir irgendwelche Kontaktdaten von dir da lassen.

**Comment by simonneutert** [comment]
Erledigt, E-Mail ist raus.

Ah, das Mehl ist der Bezug 😅 also, äh, ich schließe dieses Issue 🤣
